{
 "title": "FHIR Endpoints",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Vendor",
    "query": "select distinct case when coalesce(vendor, '') = '' then 'Unknown'\nelse vendor\nend as vendor from fhir_endpoints;"
   },
   {
    "name": "fhir_version",
    "label": "FHIR Version",
    "query": "select distinct capability_statement->>'fhirVersion' from fhir_endpoints where capability_statement->>'fhirVersion' IS NOT NULL"
   },
   {
    "name": "Resources",
    "query": "SELECT DISTINCT json_array_elements(capability_statement::json#>'{rest,0,resource}') ->> 'type' as type FROM fhir_endpoints order by type"
   }
  ]
 },
 "panels": [
  {
   "title": "Endpoint Resource Counts",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count(*),json_array_elements(capability_statement::json#>'{rest,0,resource}') ->> 'type' as type from fhir_endpoints group by json_array_elements(capability_statement::json#>'{rest,0,resource}') ->> 'type' ORDER BY type;"
    }
   ]
  },
  {
   "title": "Endpoints by Resource = $Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT url,case when coalesce(vendor, '') = '' then 'Unknown'\nelse vendor\nend as vendor FROM fhir_endpoints WHERE capability_statement#>'{rest,0,resource}' @> '[{\"type\":${Resources:json}}]'\nAND fhir_endpoints.vendor IN (${Vendor});"
    }
   ]
  },
  {
   "title": "FHIR Version = $fhir_version",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select\n  capability_statement #>> '{fhirVersion}' as fv,updated_at as \"time\", count(*)\nFROM fhir_endpoints\nWHERE capability_statement #>> '{fhirVersion}' IN ($fhir_version)\nGROUP BY fv,time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Endpoints by FHIR Version",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "select\n  count(*), capability_statement #>> '{fhirVersion}' as fv\nFROM fhir_endpoints\nGROUP BY fv\nORDER BY fv"
    }
   ]
  },
  {
   "title": "Supported Endpoint Formats",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT count(*),json_array_elements_text(capability_statement::json->'format') as format \nfrom fhir_endpoints group by json_array_elements_text(capability_statement::json->'format')\nORDER BY format;"
    }
   ]
  },
  {
   "title": "Current Successful Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.http_response <> 0\nORDER BY 1"
    }
   ]
  },
  {
   "title": "All Endpoints by Vendor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select\n  case when coalesce(vendor, '') = '' then 'Unknown'\nelse vendor\nend as vendor,updated_at as \"time\", count(*)\nFROM fhir_endpoints\nGROUP BY vendor,time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "repeat": "Vendor",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$Vendor Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM fhir_endpoints\nWHERE\n  $__timeFilter(fhir_endpoints.updated_at)\n  AND fhir_endpoints.vendor IN (${Vendor})\nORDER BY 1"
    }
   ]
  }
 ]
}