{
 "title": "Lantern Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "scrape_rate", "query": "4m" },
   {
    "name": "fhir_version",
    "label": "FHIR Version",
    "query": "select distinct value from metrics_values where labels_id IN (select id as label_id from metrics_labels where metric_name='AllEndpoints_fhir_version')"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT  \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  COUNT(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_request_responses' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Successful Response",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  COUNT(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_request_responses' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\n  AND metrics_values.value = 200\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Unsuccessful Response",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  COUNT(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_request_responses' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\n  AND metrics_values.value != 200\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Unresponsive Endpoints",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  COUNT(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_request_responses' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\n  AND metrics_values.value >= 500\n  AND metrics_values.value < 600\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Response Time Range",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  AVG(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_response_time' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\nGROUP BY time\nORDER BY time;"
    },
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  MIN(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_response_time' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\nGROUP BY time\nORDER BY time;"
    },
    {
     "rawSql": "SELECT \n  $__timeGroup(metrics_values.time, $scrape_rate),\n  MAX(metrics_values.value)\nFROM metrics_labels, metrics_values\nWHERE metrics_labels.metric_name = 'AllEndpoints_http_response_time' \n  AND metrics_labels.id = metrics_values.labels_id\n  AND $__timeFilter(metrics_values.time)\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Current FHIR Server Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT metrics_values.time, metrics_values.value\nFROM metrics_values \nWHERE metrics_values.time > (NOW() - INTERVAL '$scrape_rate')\nAND labels_id IN (select m.id as label_id FROM  metrics_labels m INNER JOIN metrics_labels e ON m.labels->>'orgName' = e.labels->>'orgName' AND e.metric_name='AllEndpoints_fhir_version' AND m.metric_name='AllEndpoints_http_response_time' \nAND e.id IN (select distinct labels_id as id from metrics_values, metrics_labels  \nWHERE metrics_values.time > (NOW() - INTERVAL '$scrape_rate') \nAND metrics_values.value IN (${fhir_version:csv}) AND metrics_values.labels_id = metrics_labels.id AND metrics_labels.metric_name = 'AllEndpoints_fhir_version'))\nGROUP BY \"time\", metrics_values.value\nORDER BY metrics_values.value;\n"
    }
   ]
  }
 ]
}