BEGIN;

DROP MATERIALIZED VIEW IF EXISTS endpoint_export_mv CASCADE;

DROP MATERIALIZED VIEW IF EXISTS fhir_endpoint_comb_mv CASCADE;

DROP MATERIALIZED VIEW IF EXISTS selected_fhir_endpoints_mv CASCADE;

COMMIT;