BEGIN;

DROP MATERIALIZED VIEW IF EXISTS mv_capstat_fields CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_capstat_values_fields CASCADE;
DROP MATERIALIZED VIEW IF EXISTS mv_capstat_values_extension CASCADE;

COMMIT;