package nppesquerier

import (
	"context"
	"fmt"
	"testing"

	th "github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/testhelper"
	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
)

func Test_ParseNPIdataLine(t *testing.T) {
	ctx := context.Background()

	// fixture file generated by running `head -20` on the provider organization .csv downloaded from http://download.cms.gov/nppes/NPI_Files.html
	reader, file1, err := csvReader(ctx, "testdata/npidata_pfile_fixture.csv")
	if err != nil {
		t.Errorf("Error reading NPI data from fixture file")
	}
	defer func() {
		err := file1.Close()
		if err != nil {
			log.Warnf("Error closing file1: %v", err)
		}
	}()

	// Remove header line
	_, err = reader.Read()
	th.Assert(t, err == nil, fmt.Sprintf("Expected Read not to throw an error, got error: %v", err))

	// Get first line in csv file
	line, err := reader.Read()
	th.Assert(t, err == nil, fmt.Sprintf("Expected Read not to throw an error, got error: %v", err))

	// "1497758544","2","","<UNAVAIL>","CUMBERLAND COUNTY HOSPITAL SYSTEM, INC","","","","","","","CAPE FEAR VALLEY HOME HEALTH AND HOSPICE","3","","","","","","","","3418 VILLAGE DR","","FAYETTEVILLE","NC","283044552","US","9106096740","","3418 VILLAGE DR","","FAYETTEVILLE","NC","283044552","US","9106096740","","05/23/2005","09/26/2011","","","","","NAGOWSKI","MICHAEL","","CEO","9106096700","251G00000X","HC0283","NC","Y","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","3401562","05","NC","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","N","","","MR.","","","","","","","","","","","","","","","","",""
	data := parseNPIdataLine(line)
	// NPI Field
	if data.NPI != "1497758544" {
		t.Errorf("Expected NPI_ID to be %s, got %s", "1497758544", data.NPI)
	}
	// Entity Type Field
	if data.Entity_Type_Code != "2" {
		t.Errorf("Expected Entity Type to be %s, got %s", "2", data.Entity_Type_Code)
	}
	// Name Field
	if data.Provider_Organization_Name_Legal_Business_Name != "CUMBERLAND COUNTY HOSPITAL SYSTEM, INC" {
		t.Errorf("Expected Name to be %s, got %s", "CUMBERLAND COUNTY HOSPITAL SYSTEM, INC", data.Provider_Organization_Name_Legal_Business_Name)
	}
	// Secondary Name Field
	if data.Provider_Other_Organization_Name != "CAPE FEAR VALLEY HOME HEALTH AND HOSPICE" {
		t.Errorf("Expected Name to be %s, got %s", "CAPE FEAR VALLEY HOME HEALTH AND HOSPICE", data.Provider_Other_Organization_Name)
	}
	// Provider_First_Line_Business_Mailing_Address
	if data.Provider_First_Line_Business_Practice_Location_Address != "3418 VILLAGE DR" {
		t.Errorf("Expected Name to be %s, got %s", "3418 VILLAGE DR", data.Provider_First_Line_Business_Practice_Location_Address)
	}
	// Provider_Second_Line_Business_Practice_Location_Address
	if data.Provider_Second_Line_Business_Practice_Location_Address != "" {
		t.Errorf("Expected Name to be %s, got %s", "", data.Provider_Second_Line_Business_Practice_Location_Address)
	}
	// Provider_Business_Practice_Location_Address_City_Name
	if data.Provider_Business_Practice_Location_Address_City_Name != "FAYETTEVILLE" {
		t.Errorf("Expected Name to be %s, got %s", "FAYETTEVILLE", data.Provider_Business_Practice_Location_Address_City_Name)
	}
	// Provider_Business_Practice_Location_Address_State_Name
	if data.Provider_Business_Practice_Location_Address_State_Name != "NC" {
		t.Errorf("Expected Name to be %s, got %s", "NC", data.Provider_Business_Practice_Location_Address_State_Name)
	}
	// Provider_Business_Practice_Location_Address_Postal_Code
	if data.Provider_Business_Practice_Location_Address_Postal_Code != "283044552" {
		t.Errorf("Expected Name to be %s, got %s", "283044552", data.Provider_Business_Practice_Location_Address_Postal_Code)
	}
	// Healthcare_Provider_Taxonomy_Code_1
	if data.Healthcare_Provider_Taxonomy_Code_1 != "251G00000X" {
		t.Errorf("Expected Name to be %s, got %s", "251G00000X", data.Healthcare_Provider_Taxonomy_Code_1)
	}
}

func Test_csvReaderContextCancel(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	lines, file2, err := csvReader(ctx, "testdata/npidata_pfile_fixture.csv")
	defer func() {
		err := file2.Close()
		if err != nil {
			log.Warnf("Error closing file2: %v", err)
		}
	}()
	th.Assert(t, errors.Cause(err) == context.Canceled, "Expected canceled context error")
	th.Assert(t, lines == nil, "expected lines returned after error to be nil")
}

func Test_BuildNPIOrgFromNPICsvLine(t *testing.T) {
	ctx := context.Background()

	// fixture file generated by running `head -20` on the provider organization .csv downloaded from http://download.cms.gov/nppes/NPI_Files.html
	reader, file3, err := csvReader(ctx, "testdata/npidata_pfile_fixture.csv")
	if err != nil {
		t.Errorf("Error reading NPI data from fixture file")
	}
	defer func() {
		err := file3.Close()
		if err != nil {
			log.Warnf("Error closing file3: %v", err)
		}
	}()

	// Remove header line
	_, err = reader.Read()
	th.Assert(t, err == nil, fmt.Sprintf("Expected Read not to throw an error, got error: %v", err))

	// Get to first line in csv file
	line, err := reader.Read()
	th.Assert(t, err == nil, fmt.Sprintf("Expected Read not to throw an error, got error: %v", err))

	// "1497758544","2","","<UNAVAIL>","CUMBERLAND COUNTY HOSPITAL SYSTEM, INC","","","","","","","CAPE FEAR VALLEY HOME HEALTH AND HOSPICE","3","","","","","","","","3418 VILLAGE DR","","FAYETTEVILLE","NC","283044552","US","9106096740","","3418 VILLAGE DR","","FAYETTEVILLE","NC","283044552","US","9106096740","","05/23/2005","09/26/2011","","","","","NAGOWSKI","MICHAEL","","CEO","9106096700","251G00000X","HC0283","NC","Y","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","3401562","05","NC","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","N","","","MR.","","","","","","","","","","","","","","","","",""
	data := parseNPIdataLine(line)
	npi_org, err := buildNPIOrgFromNPICsvLine(data)
	if err != nil {
		t.Errorf("Received error: %+v", err)
	}
	// NPI Field
	if npi_org.NPI_ID != "1497758544" {
		t.Errorf("Expected NPI_ID to be %s, got %s", "1497758544", npi_org.NPI_ID)
	}
	// Name Field
	if npi_org.Name != "CUMBERLAND COUNTY HOSPITAL SYSTEM, INC" {
		t.Errorf("Expected Name to be %s, got %s", "CUMBERLAND COUNTY HOSPITAL SYSTEM, INC", npi_org.Name)
	}
	// Secondary Name Field
	if npi_org.SecondaryName != "CAPE FEAR VALLEY HOME HEALTH AND HOSPICE" {
		t.Errorf("Expected Name to be %s, got %s", "CAPE FEAR VALLEY HOME HEALTH AND HOSPICE", npi_org.SecondaryName)
	}
	// 	Location.Address1
	if npi_org.Location.Address1 != "3418 VILLAGE DR" {
		t.Errorf("Expected Name to be %s, got %s", "3418 VILLAGE DR", npi_org.Location.Address1)
	}
	// Location.Address2
	if npi_org.Location.Address2 != "" {
		t.Errorf("Expected Name to be %s, got %s", "", npi_org.Location.Address2)
	}
	// Location.City
	if npi_org.Location.City != "FAYETTEVILLE" {
		t.Errorf("Expected Name to be %s, got %s", "FAYETTEVILLE", npi_org.Location.City)
	}
	// Location.State
	if npi_org.Location.State != "NC" {
		t.Errorf("Expected Name to be %s, got %s", "NC", npi_org.Location.State)
	}
	// Location.ZipCode
	if npi_org.Location.ZipCode != "283044552" {
		t.Errorf("Expected Name to be %s, got %s", "283044552", npi_org.Location.ZipCode)
	}
	// Taxonomy
	if npi_org.Taxonomy != "251G00000X" {
		t.Errorf("Expected Name to be %s, got %s", "251G00000X", npi_org.Taxonomy)
	}
}
